---
# A list of variables that must be set for all elements
preamble:
    LC_ALL: POSIX
    WANDER: /wander
    PATH: /tools/bin:/bin:/usr/bin
    WANDER_TGT: '{arch}-wander-linux-gnu'
# The user that must run this section
user: wander
# The elements, each representing one unit to execute
elements:
    binutils_1:
        description: Binutils (Pass 1)
        package: binutils
        folder: build
        commands:
            preparation:
                - ../configure --prefix=/tools
                               --with-sysroot=$WANDER
                               --with-lib-path=/tools/lib
                               --target=$WANDER_TGT
                               --disable-nls
                               --disable-werror
            compilation:
                - make
            configuration:
                - case $(uname -m) in
                    x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
                  esac
            installation:
                - make install
    gcc_1:
        description: GCC (Pass 1)
        package: gcc
        modules:
            - mpfr
            - gmp
            - mpc
        folder: build
        commands:
            setup:
                - for file in gcc/config/{linux,i386/linux{,64}}.h;
                  do (
                    cp -uv $file{,.orig};
                    sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g'
                        -e 's@/usr@/tools@g' $file.orig > $file;
                    printf '#undef STANDARD_STARTFILE_PREFIX_1\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> $file;
                    touch $file.orig);
                  done
                - case $(uname -m) in
                    x86_64) sed -e '/m64=/s/lib64/lib/'
                                -i.orig gcc/config/i386/t-linux64
                    ;;
                  esac
            preparation:
                - ../configure --target=$WANDER_TGT
                               --prefix=/tools
                               --with-glibc-version=2.11
                               --with-sysroot=$WANDER
                               --with-newlib
                               --without-headers
                               --with-local-prefix=/tools
                               --with-native-system-header-dir=/tools/include
                               --disable-nls
                               --disable-shared
                               --disable-multilib
                               --disable-decimal-float
                               --disable-threads
                               --disable-libatomic
                               --disable-libgomp
                               --disable-libquadmath
                               --disable-libssp
                               --disable-libvtv
                               --disable-libstdcxx
                               --enable-languages=c,c++
            compilation:
                - make
            installation:
                - make install
    linux:
        package: linux
        commands:
            preparation:
                - make mrproper
            installation:
                - make INSTALL_HDR_PATH=dest headers_install
                - cp -rv dest/include/* /tools/include
    glibc:
        package: glibc
        folder: build
        commands:
            preparation:
                - ../configure --prefix=/tools
                               --host=$WANDER_TGT
                               --build=$(../scripts/config.guess)
                               --enable-kernel=3.2
                               --with-headers=/tools/include
            compilation:
                - make
            installation:
                - make install
            validation:
                - echo 'int main(){}' > dummy.c
                - $WANDER_TGT-gcc dummy.c
                - "readelf -l a.out | grep ': /tools'"
            cleanup:
                - rm -v dummy.c a.out
        result:
            - "[Requesting program interpreter: /tools/lib64/ld-linux-x86-64.so.2]"
            - "[Requesting program interpreter: /tools/lib/ld-linux.so.2]"
    libstdc++:
        description: Libstdc++ (from GCC)
        package: gcc
        folder: build
        commands:
            preparation:
                - ../libstdc++-v3/configure --host=$WANDER_TGT
                                            --prefix=/tools
                                            --disable-multilib
                                            --disable-nls
                                            --disable-libstdcxx-threads
                                            --disable-libstdcxx-pch
                                            --with-gxx-include-dir=/tools/$WANDER_TGT/include/c++/9.2.0
            compilation:
                - make
            installation:
                - make install
    binutils_2:
        description: Binutils (Pass 2)
        package: binutils
        folder: build
        commands:
            preparation:
                - CC=$WANDER_TGT-gcc
                  AR=$WANDER_TGT-ar
                  RANLIB=$WANDER_TGT-ranlib
                  ../configure --prefix=/tools
                               --disable-nls
                               --disable-werror
                               --with-lib-path=/tools/lib
                               --with-sysroot
            compilation:
                - make
            installation:
                - make install
                - make -C ld clean
                - "make -C ld LIB_PATH=/usr/lib:/lib"
                - cp -v ld/ld-new /tools/bin
    gcc_2:
        description: GCC (Pass 2)
        package: gcc
        modules:
            - mpfr
            - gmp
            - mpc
        folder: build
        commands:
            setup:
                - cat gcc/limitx.h gcc/glimits.h gcc/limity.h >
                    `dirname $($WANDER_TGT-gcc -print-libgcc-file-name)`/include-fixed/limits.h
                - for file in gcc/config/{linux,i386/linux{,64}}.h;
                  do (
                    cp -uv $file{,.orig};
                    sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g'
                        -e 's@/usr@/tools@g' $file.orig > $file;
                    printf '#undef STANDARD_STARTFILE_PREFIX_1\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file;
                    touch $file.orig);
                  done
                - case $(uname -m) in
                    x86_64) sed -e '/m64=/s/lib64/lib/'
                                -i.orig gcc/config/i386/t-linux64
                    ;;
                  esac
            preparation:
                - CC=$WANDER_TGT-gcc
                  CXX=$WANDER_TGT-g++
                  AR=$WANDER_TGT-ar
                  RANLIB=$WANDER_TGT-ranlib
                  ../configure --prefix=/tools
                               --with-local-prefix=/tools
                               --with-native-system-header-dir=/tools/include
                               --enable-languages=c,c++
                               --disable-libstdcxx-pch
                               --disable-multilib
                               --disable-bootstrap
                               --disable-libgomp
            compilation:
                - make
            installation:
                - make install
                - ln -sv gcc /tools/bin/cc
            validation:
                - echo 'int main(){}' > dummy.c
                - cc dummy.c
                - "readelf -l a.out | grep ': /tools'"
            cleanup:
                - rm -v dummy.c a.out
        result:
            - "[Requesting program interpreter: /tools/lib64/ld-linux-x86-64.so.2]"
            - "[Requesting program interpreter: /tools/lib/ld-linux.so.2]"
    tcl:
        package: tcl
        folder: unix
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - TZ=UTC make test
            installation:
                - make install
                - chmod -v u+w /tools/lib/libtcl8.6.so
                - make install-private-headers
                - ln -sv tclsh8.6 /tools/bin/tclsh
    expect:
        package: expect
        commands:
            preparation:
                - cp -v configure{,.orig}
                - sed 's:/usr/local/bin:/bin:' configure.orig > configure
                - ./configure --prefix=/tools
                              --with-tcl=/tools/lib
                              --with-tclinclude=/tools/include
            compilation:
                - make
            testing:
                - make test
            installation:
                - make SCRIPTS="" install
    dejagnu:
        package: dejagnu
        commands:
            preparation:
                - ./configure --prefix=/tools
            installation:
                - make install
            validation:
                - make check
    m4:
        package: m4
        commands:
            preparation:
                - sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
                - echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    ncurses:
        package: ncurses
        commands:
            preparation:
                - sed -i s/mawk// configure
                - ./configure --prefix=/tools
                              --with-shared
                              --without-debug
                              --without-ada
                              --enable-widec
                              --enable-overwrite
            compilation:
                - make
            installation:
                - make install
                - ln -s libncursesw.so /tools/lib/libncurses.so
    bash:
        package: bash
        commands:
            preparation:
                - ./configure --prefix=/tools
                              --without-bash-malloc
            compilation:
                - make
            testing:
                - make tests
            installation:
                - make install
                - ln -sv bash /tools/bin/sh
    bison:
        package: bison
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    bzip2:
        package: bzip2
        commands:
            compilation:
                - make
            installation:
                - make PREFIX=/tools install
    coreutils:
        package: coreutils
        commands:
            preparation:
                - ./configure --prefix=/tools
                              --enable-install-program=hostname
            compilation:
                - make
            testing:
                - make RUN_EXPENSIVE_TESTS=yes check
            installation:
                - make install
    diffutils:
        package: diffutils
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    file:
        package: file
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    findutils:
        package: findutils
        commands:
            preparation:
                - sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' gl/lib/*.c
                - "sed -i '/unistd/a #include <sys/sysmacros.h>' gl/lib/mountlist.c"
                - echo "#define _IO_IN_BACKUP 0x100" >> gl/lib/stdio-impl.h
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    gawk:
        package: gawk
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    gettext:
        package: gettext
        commands:
            preparation:
                - ./configure --disable-shared
            compilation:
                - make
            installation:
                - cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /tools/bin
    grep:
        package: grep
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    gzip:
        package: gzip
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    make:
        package: make
        commands:
            preparation:
                - sed -i '211,217 d; 219,229 d; 232 d' glob/glob.c
                - ./configure --prefix=/tools
                              --without-guile
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    patch:
        package: patch
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    perl:
        package: perl
        commands:
            preparation:
                - sh Configure -des
                               -Dprefix=/tools
                               -Dlibs=-lm
                               -Uloclibpth
                               -Ulocincpth
            compilation:
                - make
            installation:
                - cp -v perl cpan/podlators/scripts/pod2man /tools/bin
                - mkdir -pv /tools/lib/perl5/5.30.0
                - cp -Rv lib/* /tools/lib/perl5/5.30.0
    python:
        package: python
        commands:
            preparation:
                - sed -i '/def add_multiarch_paths/a \        return' setup.py
                - ./configure --prefix=/tools
                              --without-ensurepip
            compilation:
                - make
            installation:
                - make install
    sed:
        package: sed
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    tar:
        package: tar
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    texinfo:
        package: texinfo
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    util-linux:
        package: util-linux
        commands:
            preparation:
                - ./configure --prefix=/tools
                              --without-python
                              --disable-makeinstall-chown
                              --without-systemdsystemunitdir
                              --without-ncurses
                              PKG_CONFIG=""
            compilation:
                - make
            installation:
                - make install
    xz:
        package: xz
        commands:
            preparation:
                - ./configure --prefix=/tools
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
# A list of commands to be run when this section ends
cleanup:
    - strip --strip-debug /tools/lib/*
    - /usr/bin/strip --strip-unneeded /tools/{,s}bin/*
    - rm -rf /tools/{,share}/{info,man,doc}
    - find /tools/{lib,libexec} -name \*.la -delete
    - chown -R root:root $WANDER/tools
...
