---
# A list of variables that must be set for all elements
preamble:
    HOME: /root
    TERM: $TERM
    PS1: '(wander chroot) \u:\w\$ '
    PATH: '/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin'
    WANDER: /wander
    ZONEINFO: /usr/share/zoneinfo
# The user that must run this section
user: chroot
# The elements, each representing one unit to execute
elements:
    zlib:
        package: zlib
        commands:
            preparation:
                - ./configure --prefix=/usr
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
            cleanup:
                - mv -v /usr/lib/libz.so.* /lib
                - ln -sfv ../../lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so
    file:
        package: file
        commands:
            preparation:
                - ./configure --prefix=/usr
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    readline:
        package: readline
        commands:
            setup:
                - sed -i '/MV.*old/d' Makefile.in
                - sed -i '/{OLDSUFF}/c:' support/shlib-install
            preparation:
                - ./configure --prefix=/usr
                              --disable-static
                              --docdir=/usr/share/doc/readline-8.0
            compilation:
                - make SHLIB_LIBS="-L/tools/lib -lncursesw"
            installation:
                - make SHLIB_LIBS="-L/tools/lib -lncursesw" install
            cleanup:
                - mv -v /usr/lib/lib{readline,history}.so.* /lib
                - chmod -v u+w /lib/lib{readline,history}.so.*
                - ln -sfv ../../lib/$(readlink /usr/lib/libreadline.so) /usr/lib/libreadline.so
                - ln -sfv ../../lib/$(readlink /usr/lib/libhistory.so ) /usr/lib/libhistory.so
                - install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.0
    m4:
        package: m4
        commands:
            preparation:
                - sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
                - echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
                - ./configure --prefix=/usr
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
...
