---
# A list of variables that must be set for all elements
preamble:
    HOME: /root
    TERM: $TERM
    PS1: '(wander chroot) \u:\w\$ '
    PATH: '/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin'
    WANDER: /wander
    ZONEINFO: /usr/share/zoneinfo
# The user that must run this section
user: chroot
# The elements, each representing one unit to execute
elements:
    zlib:
        package: zlib
        sbu: 0.1
        commands:
            preparation:
                - ./configure --prefix=/usr
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
            cleanup:
                - mv -v /usr/lib/libz.so.* /lib
                - ln -sfv ../../lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so
    file:
        package: file
        sbu: 0.1
        commands:
            preparation:
                - ./configure --prefix=/usr
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    readline:
        package: readline
        sbu: 0.1
        commands:
            setup:
                - sed -i '/MV.*old/d' Makefile.in
                - sed -i '/{OLDSUFF}/c:' support/shlib-install
            preparation:
                - ./configure --prefix=/usr
                              --disable-static
                              --docdir=/usr/share/doc/readline-8.0
            compilation:
                - make SHLIB_LIBS="-L/tools/lib -lncursesw"
            installation:
                - make SHLIB_LIBS="-L/tools/lib -lncursesw" install
            cleanup:
                - mv -v /usr/lib/lib{readline,history}.so.* /lib
                - chmod -v u+w /lib/lib{readline,history}.so.*
                - ln -sfv ../../lib/$(readlink /usr/lib/libreadline.so) /usr/lib/libreadline.so
                - ln -sfv ../../lib/$(readlink /usr/lib/libhistory.so ) /usr/lib/libhistory.so
                - install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.0
    m4:
        package: m4
        sbu: 0.4
        commands:
            preparation:
                - sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
                - echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
                - ./configure --prefix=/usr
            compilation:
                - make
            testing:
                - make check
            installation:
                - make install
    bc:
        package: bc
        sbu: 0.1
        commands:
            preparation:
                - PREFIX=/usr CC=gcc CFLAGS="-std=c99" ./configure.sh -G -O3
            compilation:
                - make
            testing:
                - make test
            installation:
                - make install
    binutils:
        package: binutils
        sbu: 7.4
        folder: build
        commands:
            setup:
                - sed -i '/@\tincremental_copy/d' gold/testsuite/Makefile.in
            preparation:
                - ../configure --prefix=/usr
                               --enable-gold
                               --enable-ld=default
                               --enable-plugins
                               --enable-shared
                               --disable-werror
                               --enable-64-bit-bfd
                               --with-system-zlib
            compilation:
                - make tooldir=/usr
            testing:
                - make -k check
            installation:
                - make tooldir=/usr install
    gmp:
        package: gmp
        sbu: 1.2
        commands:
            preparation:
                - ./configure --prefix=/usr
                              --enable-cxx
                              --disable-static
                              --docdir=/usr/share/doc/gmp-6.1.2
            compile:
                - make
                - make html
            testing:
                - make check 2>&1 | tee gmp-check-log
                - awk '/# PASS:/{total+=$3} ; END{print total}' gmp-check-log
            installation:
                - make install
                - make install-html
    mpfr:
        package: mpfr
        sbu: 0.9
        commands:
            preparation:
                - ./configure --prefix=/usr
                              --disable-static
                              --enable-thread-safe
                              --docdir=/usr/share/doc/mpfr-4.0.2
            compilation:
                - make
                - make html
            testing:
                - make check
            installation:
                - make install
                - make install-html
    mpc:
        package: mpc
        sbu: 0.3
        commands:
            preparation:
                - ./configure --prefix=/usr
                              --disable-static
                              --docdir=/usr/share/doc/mpc-1.1.0
            compilation:
                - make
                - make html
            testing:
                - make check
            installation:
                - make install
                - make install-html
    shadow:
        package: shadow
        sbu: 0.2
        commands:
            setup:
                - sed -i 's/groups$(EXEEXT) //' src/Makefile.in
                - find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
                - find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
                - find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;
                - sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@'
                         -e 's@/var/spool/mail@/var/mail@' etc/login.defs
                - sed -i 's@DICTPATH.*@DICTPATH\t/lib/cracklib/pw_dict@' etc/login.defs
                - sed -i 's/1000/999/' etc/useradd
            preparation:
                - ./configure --sysconfdir=/etc
                              --with-group-name-max-length=32
            compilation:
                - make
            installation:
                - make install
            cleanup:
                - mv -v /usr/bin/passwd /bin
                - pwconv
                - grpconv
    gcc:
        package: gcc
        sbu: 95.0
        folder: build
        commands:
            setup:
                - case $(uname -m) in
                    x86_64) sed -e '/m64=/s/lib64/lib/' \
                                -i.orig gcc/config/i386/t-linux64
                    ;;
                  esac
            preparation:
                - SED=sed ../configure --prefix=/usr
                                       --enable-languages=c,c++
                                       --disable-multilib
                                       --disable-bootstrap
                                       --with-system-zlib
            compilation:
                - make
            testing:
                - ulimit -s 32768
                - chown -Rv nobody .
                - su nobody -s /bin/bash -c "PATH=$PATH make -k check"
                - ../contrib/test_summary | grep -A7 Summary
            installation:
                - make install
                - rm -rf /usr/lib/gcc/$(gcc -dumpmachine)/9.2.0/include-fixed/bits/
                - chown -v -R root:root /usr/lib/gcc/*linux-gnu/9.2.0/include{,-fixed}
                - ln -sv ../usr/bin/cpp /lib
                - ln -sv gcc /usr/bin/cc
                - install -v -dm755 /usr/lib/bfd-plugins
                - ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/9.2.0/liblto_plugin.so /usr/lib/bfd-plugins/
            validation:
                - echo 'int main(){}' > dummy.c
                - cc dummy.c -v -Wl,--verbose &> dummy.log
                - "readelf -l a.out | grep ': /lib'"
            cleanup:
                - "readelf -l a.out | grep ': /lib'"
                - grep -o '/usr/lib.*/crt[1in].*succeeded' dummy.log
                - grep -B4 '^ /usr/include' dummy.log
                - grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
                - grep "/lib.*/libc.so.6 " dummy.log
                - grep found dummy.log
                - rm -v dummy.c a.out dummy.log
                - mkdir -pv /usr/share/gdb/auto-load/usr/lib
                - mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib
        result:
            - "[Requesting program interpreter: /tools/lib64/ld-linux-x86-64.so.2]"
            - "[Requesting program interpreter: /tools/lib/ld-linux.so.2]"
...
