---
# A list of variables that must be set for all elements
preamble:
    HOME: /root
    TERM: $TERM
    PS1: '(wander chroot) \u:\w\$ '
    PATH: '/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin'
    WANDER: /wander
# The user that must run this section
user: chroot
# A list of commands to be run before this stage begins
init:
    - mkdir -pv /{bin,boot,etc/{opt,sysconfig},home,lib/firmware,mnt,opt}
    - mkdir -pv /{media/{floppy,cdrom},sbin,srv,var}
    - install -dv -m 0750 /root
    - install -dv -m 1777 /tmp /var/tmp
    - mkdir -pv /usr/{,local/}{bin,include,lib,sbin,src}
    - mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man}
    - mkdir -v  /usr/{,local/}share/{misc,terminfo,zoneinfo}
    - mkdir -v  /usr/libexec
    - mkdir -pv /usr/{,local/}share/man/man{1..8}
    - mkdir -v  /usr/lib/pkgconfig
    - case $(uname -m) in
        x86_64) mkdir -v /lib64 ;;
      esac
    - mkdir -v /var/{log,mail,spool}
    - ln -sv /run /var/run
    - ln -sv /run/lock /var/lock
    - mkdir -pv /var/{opt,cache,lib/{color,misc,locate},local}
    - ln -sv /tools/bin/{bash,cat,chmod,dd,echo,ln,mkdir,pwd,rm,stty,touch} /bin
    - ln -sv /tools/bin/{env,install,perl,printf} /usr/bin
    - ln -sv /tools/lib/libgcc_s.so{,.1} /usr/lib
    - ln -sv /tools/lib/libstdc++.{a,so{,.6}} /usr/lib
    - ln -sv bash /bin/sh
    - ln -sv /proc/self/mounts /etc/mtab
    - printf "root:x:0:0:root:/root:/bin/bash\n
              bin:x:1:1:bin:/dev/null:/bin/false\n
              daemon:x:6:6:Daemon User:/dev/null:/bin/false\n
              messagebus:x:18:18:D-Bus Message Daemon User:/var/run/dbus:/bin/false\n
              systemd-bus-proxy:x:72:72:systemd Bus Proxy:/:/bin/false\n
              systemd-journal-gateway:x:73:73:systemd Journal Gateway:/:/bin/false\n
              systemd-journal-remote:x:74:74:systemd Journal Remote:/:/bin/false\n
              systemd-journal-upload:x:75:75:systemd Journal Upload:/:/bin/false\n
              systemd-network:x:76:76:systemd Network Management:/:/bin/false\n
              systemd-resolve:x:77:77:systemd Resolver:/:/bin/false\n
              systemd-timesync:x:78:78:systemd Time Synchronization:/:/bin/false\n
              systemd-coredump:x:79:79:systemd Core Dumper:/:/bin/false\n
              nobody:x:99:99:Unprivileged User:/dev/null:/bin/false" > /etc/passwd
    - printf "root:x:0:\n
              bin:x:1:daemon\n
              sys:x:2:\n
              kmem:x:3:\n
              tape:x:4:\n
              tty:x:5:\n
              daemon:x:6:\n
              floppy:x:7:\n
              disk:x:8:\n
              lp:x:9:\n
              dialout:x:10:\n
              audio:x:11:\n
              video:x:12:\n
              utmp:x:13:\n
              usb:x:14:\n
              cdrom:x:15:\n
              adm:x:16:\n
              messagebus:x:18:\n
              systemd-journal:x:23:\n
              input:x:24:\n
              mail:x:34:\n
              kvm:x:61:\n
              systemd-bus-proxy:x:72:\n
              systemd-journal-gateway:x:73:\n
              systemd-journal-remote:x:74:\n
              systemd-journal-upload:x:75:\n
              systemd-network:x:76:\n
              systemd-resolve:x:77:\n
              systemd-timesync:x:78:\n
              systemd-coredump:x:79:\n
              wheel:x:97:\n
              nogroup:x:99:\n
              users:x:999:" > /etc/group
    - touch /var/log/{btmp,lastlog,faillog,wtmp}
    - chgrp -v utmp /var/log/lastlog
    - chmod -v 664  /var/log/lastlog
    - chmod -v 600  /var/log/btmp
# The elements, each representing one unit to execute
elements:
    linux:
        package: linux
        commands:
            preparation:
                - make mrproper
            installation:
                - make INSTALL_HDR_PATH=dest headers_install
                - find dest/include \( -name .install -o -name ..install.cmd \) -delete
                - cp -rv dest/include/* /usr/include
    man-pages:
        package: man-pages
        commands:
            installation:
                - make install
...
